# Generated by Django 3.2.5 on 2021-07-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoListApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created2',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
